name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          uv pip install --system --requirement requirements.txt
          uv pip install --system mypy ruff

      - name: Lint with Ruff
        run: ruff check src

      - name: Type check with mypy
        run: mypy --config-file mypy-ci.ini src

      - name: Run critical trading backtests
        run: |
          python -m pytest tests/test_trade_stock_e2e.py tests/test_backtest3.py

      - name: Run unit tests
        run: |
          python -m pytest tests \
            --ignore=tests/integ \
            --ignore=tests/test_trade_stock_e2e.py \
            --ignore=tests/test_backtest3.py \
            -m "not integration"

      - name: Run integration tests
        run: |
          python -m pytest tests/integ
          python -m pytest -m integration --ignore=tests/integ
